### ISSUE TITLE
角色与权限

### ISSUE THREAD

**Issue by HoshinoTented** [project-mirai/mirai-plugin-center#39]
Role 应当被细分为 Permission，并且 User 也不应该只拥有一个 Role，考虑加表或者修改表结构

**Comment by HoshinoTented** [comment]
+ [ ] 新增 RoleEntity
+ [ ] 新增 RolePermissionEntity

## Role Entity
role 表的条目，包含：

* id: 主键
* name; role 名称（通常是人类可读的）
* owner: 添加该 role 的用户
* log: 关于该 role 的历史链

## RolePermissionEntity
role_permission 表的条目，包含：

* role: role id
* permission: 内置的 permission id

该条目用于建立 role 和 permission 的联系，如某个 role 拥有某个 permission

**Comment by HoshinoTented** [comment]
随后集成一下 RoleService，把这些操作包装一下

**Comment by HoshinoTented** [comment]
@jasonczc 有什么建议吗

**Comment by jasonczc** [comment]
设计上应该没问题，我觉得很好

**Comment by HoshinoTented** [comment]
> 设计上应该没问题，我觉得很好

那就是很有问题

**Comment by HoshinoTented** [comment]
主要灵感是 C# 的 RoleManager，我感觉那个设计很好，但是 Spring 这边找不到类似的

**Comment by Eiriksgata** [comment]
这种标准不应该是RBAC模型设计吗？。

**Comment by Eiriksgata** [comment]
Spring系列的关于RBAC模型的相关技术支持有Spring Security，不过一度被我同事吐槽过于麻烦而且仅支持单一语言而没有选用。

**Comment by HoshinoTented** [comment]
> Spring系列的关于RBAC模型的相关技术支持有Spring Security，不过一度被我同事吐槽过于麻烦而且仅支持单一语言而没有选用。

我看看

**Comment by HoshinoTented** [comment]
我不管，自己造轮子好了
