### ISSUE TITLE
Pr #41 的后续工作

### ISSUE THREAD

**Issue by HoshinoTented** [project-mirai/mirai-plugin-center#44]
目前找到的问题是：

* 删除当前用户相关的内容无法立刻生效：
  因为当前用户的实例是存在 Session 里的，没有办法被 Hibernate 刷新。

**Comment by HoshinoTented** [comment]
解决方案：

* Session 内只保存 uid，需要的时候重新获取

**Comment by HoshinoTented** [comment]
存 uid 的话可以解决问题。但是 UserEntity 内部的 Collection 默认是不缓存的。
如果根据互联网上的资料简单地添加 Cache 注解会有问题：

* **只** 通过 CrudRepository 更新 Collection 所引用的内容时不会刷新。（数据库有更新，缓存没有）
* **只** 通过更新 entity 中的 Collection 时没有任何作用。（数据库无更新，缓存也没有）

只有两者都使用的时候才会成功。

**Comment by HoshinoTented** [comment]
还有，存  uid 的时候需要一个 UserRepo，我选择放 Session 里了

**Comment by Him188** [comment]
#41

**Comment by HoshinoTented** [comment]
#45

**Comment by HoshinoTented** [comment]
其他 Service 应该使用 UserService 还是 UserRepo 来操纵 UserEntity？

**Comment by HoshinoTented** [comment]
我比较喜欢 UserService，但比较怕递归依赖

**Comment by HoshinoTented** [comment]
> 我比较喜欢 UserService，但比较怕递归依赖

当然，出现递归依赖就意味着这个 Service 太 _大_ 了
